### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by JonnyTech** [atluxity/pkg-clickshare#3]
Since Barco have dropped support for Linux, is this project now dead?

https://www.barco.com/en/mybarco/mysupport/productsupport/knowledgebase?kbid=1191&productid=b21eda55-0837-4478-87f6-68d51b71e405

> UPDATE : Support for the Linux client has ended as it requires an enormous effort to support all the Linux distributions and their quick updates, while the usage rate of the Linux client was/is very limited. 
> 
> However, the customer can still share to a CSC-1 using the MirrorOp extension within the Google Chrome browser or to a CSE-200 using the Google Cast extension within the Google Chrome browser on Ubuntu.

**Comment by petterreinholdtsen** [comment]
[JonnyTech]

> Since Barco have dropped support for Linux, is this project now dead?

Well, for me the project was dead when Barco did not allow us to wrap up
the needed software and distribute it with Debian setup to get it
working out of the box.  Without the legal rights to distribute the
programs, it is hard to make a deb with the software.  And without a
sensible source to use for downloading to individual machines, it become
impossible.

But such is life when wasting money on non-free hardware solutions.  One
is at the mercy of the vendor and it is just a question of time when he
leave your platform out in the dark.  And apparently that time was now
for Linux.

See also <URL: https://bugs.debian.org/820587 >.

## 

Happy hacking
Petter Reinholdtsen
